### ISSUE TITLE
API lacks a boolean field

### ISSUE THREAD

**Issue by pyrech** [ternel/weekend-website#10]
It would be cool to have a boolean property inside the API to simply determine if it's the weekend or not. Something like :
```json
{
  "text": "Officiellement non, mais c'est comme si.",
  "subtext": "",
  "is_weekend": false,
}
```

**Comment by ternel** [comment]
I'll review your PR as soon as you make it.

**Comment by lyrixx** [comment]
This issue can be closed ;)
