### ISSUE TITLE
Broken API endpoint ?

### ISSUE THREAD

**Issue by massix** [ternel/weekend-website#15]
Bonjour,
it seems like after the recent update the api endpoint has stopped working. It might be related with the fabric configuration, mapping both the `apiAction` and the `indexAction` to the `/` endpoint? I'm no expert though so I can't confirm :)

https://github.com/ternel/weekend-website/blob/master/config/routes.yaml#L5

Thanks and have a nice weekend!

**Comment by ternel** [comment]
Hello :)
It's fixed! -> https://estcequecestbientotleweekend.fr/api
And it's https now \o/

**Comment by massix** [comment]
Thanks, you're the best!

Je te souhaite un excellent week-end !
