### ISSUE TITLE
SSL certificate error 

### ISSUE THREAD

**Issue by pgrimaud** [ternel/weekend-website#17]
Can you renew SSL certificate?

![image](https://user-images.githubusercontent.com/1866496/57806265-0e7a3800-775f-11e9-957e-339ba991c3f5.png)

Thanks 😄

**Comment by ternel** [comment]
oops :)

Done, thx for the ping! :beer:

**Comment by pgrimaud** [comment]
Awesome! Thanks dude. ❤️ 


This is for you : 
![image](https://user-images.githubusercontent.com/1866496/57812511-8cddd680-776d-11e9-8a8b-7e3b9e4754e1.png)
