### ISSUE TITLE
it's broken, fix plz

### ISSUE THREAD

**Issue by jduval** [ternel/weekend-website#8]
at 15:27 it displays "C'est le week-end ! \o/"

It's not. At all.

![screenshot from 2016-04-01 15 31 40](https://cloud.githubusercontent.com/assets/1597299/14208290/f5411786-f81e-11e5-934b-9a166c253dc7.png)

fix plz

**Comment by ternel** [comment]
It seems that it will be fixed tomorrow 
https://github.com/ternel/weekend-website/blob/master/src/Ternel/Weekend.php#L15

¯\_(ツ)_/¯
